name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*-prd'

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    environment:
      name: Prd
      url: 'https://example.com'

    steps:
      - name: Simulate Deployment
        run: echo "deployed!"
